### ISSUE TITLE
Z azis not working correctly

### ISSUE THREAD

**Issue by JefroB** [Printrbot/Marlin#15]
I just flashed my firmware with Revision F version 5, but now when I try to home the Z axis in Cura, the probe only goes up. Also, if I press either Z -10 or the Z +10 in cura, the probe goes up.

**Comment by j-laird** [comment]
I tested the operation of each axis on a rev F4 board - perhaps you flashed a rev D board with this firmware which is meant for rev Fx?

More detail about your printer, rev of Printrboard, and precious firmware used might be helpful.

**Comment by JefroB** [comment]
I found what the issue was. When I placed the jumper that I moved to short the boot pins after flashing the firmware back to it's original pins, I didn't put it back on the proper pins. It was causing the auto-leveling probe to stay on. Once I moved it back to the correct pins, everything worked correctly.

**Comment by alana314** [comment]
8 years later - I just had this issue and it was because I used the revision F hardware instead of unified-v3.cpp.hex. Thanks for keeping this repo around, and for whomever hosts printrbottalk.com. I couldn't use the GUI app but was able to flash on mac with dfu-programmer. I may be one of the only ones using this printer 11 years after its release!
